version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: chatdocs-dictionary
    path: ./.cspell/chatdocs-dictionary.txt
    addWords: true
dictionaries:
  - chatdocs-dictionary
words: []
ignoreWords: []
import: []
