# https://taskfile.dev

version: "3"

vars:
  CMD: '{{if eq .OS "Windows_NT"}}C:/Windows/System32/cmd.exe{{end}}'
  DOCKER: '{{if eq .OS "Windows_NT"}}C:/Program Files/Docker/Docker/resources/bin/docker.exe{{else}}docker{{end}}'
  RM1: '{{if eq .OS "Windows_NT"}}powershell -NoProfile -Command Remove-Item -Recurse -Force {{else}}rm -rf{{end}}'
  RM: '{{if eq .OS "Windows_NT"}}cmd /d /c rmdir /q /s{{else}}rm -rf{{end}}'
  PY_EXE_PATH: '{{if eq .OS "Windows_NT"}}C:/Windows/py.exe{{end}}'
  PY: '{{if eq .OS "Windows_NT"}}"{{fromSlash .PY_EXE_PATH}}" -3{{else}}python3{{end}}'
  PIP: '{{if eq .OS "Windows_NT"}}"{{fromSlash .PY_EXE_PATH}}" -3 -m pip{{else}}pip3{{end}}'
  PROJECT_DIR: "{{.USER_WORKING_DIR}}"
  KILL: '{{if eq .OS "Windows_NT"}}powershell -NoProfile -Command Stop-Process -Force -EV Err -EA SilentlyContinue -Name{{else}}pkill -f{{end}}'
  SHELL: '{{if eq .OS "Windows_NT"}}c -NoProfile -Command "{{else}}sh -c "{{end}}'
  VENV_PATH: "{{.PROJECT_DIR}}/.venv"
  VENV_ACTIVATE_PATH: '{{if eq .OS "Windows_NT"}}{{.VENV_PATH}}/Scripts/activate.bat{{else}}{{.VENV_PATH}}/Scripts/activate{{end}}'
  VENV_PYTHON: '{{if eq .OS "Windows_NT"}}{{.VENV_PATH}}/Scripts/python.exe{{else}}{{.VENV_PATH}}/Scripts/activate{{end}}'
  VENV_PIP: '{{if eq .OS "Windows_NT"}}{{.VENV_PATH}}/Scripts/pip.exe{{else}}{{.VENV_PATH}}/Scripts/pip3{{end}}'
  VENV_PY: '{{if eq .OS "Windows_NT"}}"{{fromSlash .CMD}}" call /D /C "{{fromSlash .VENV_ACTIVATE_PATH}}" && "{{fromSlash .VENV_PYTHON}}"{{end}}'

tasks:
  default:
    cmds:
      - cmd: '{{.PY}} -m venv "{{fromSlash .VENV_PATH}}"'
        ignore_error: true
      - "{{.VENV_PY}} -m pip install -r requirements.txt"
    silent: false
